export class PlanningPrDayModel {
  id: number;
  siteName: string;
  siteId: number;
  weekDay: number;
  date: string;
  planText: string;
  planHours: number;
  actualHours: number;
  difference: number;
  pauseMinutes: number;
  message: number;
  workDayStarted: boolean;
  workDayEnded: boolean;
  planHoursMatched: boolean
  plannedStartOfShift1: number;
  plannedEndOfShift1: number;
  plannedBreakOfShift1: number;
  plannedStartOfShift2: number;
  plannedEndOfShift2: number;
  plannedBreakOfShift2: number;
  plannedStartOfShift3: number;
  plannedEndOfShift3: number;
  plannedBreakOfShift3: number;
  plannedStartOfShift4: number;
  plannedEndOfShift4: number;
  plannedBreakOfShift4: number;
  plannedStartOfShift5: number;
  plannedEndOfShift5: number;
  plannedBreakOfShift5: number;
  isDoubleShift: boolean;
  onVacation: boolean;
  sick: boolean;
  otherAllowedAbsence: boolean;
  absenceWithoutPermission: boolean;
  start1StartedAt: string;
  stop1StoppedAt: string;
  start2StartedAt: string;
  stop2StoppedAt: string;
  start3StartedAt: string;
  stop3StoppedAt: string;
  start4StartedAt: string;
  stop4StoppedAt: string;
  start5StartedAt: string;
  stop5StoppedAt: string;
  break1Shift: number;
  break2Shift: number;
  commentOffice: string;
  workerComment: string;
  sumFlexStart: number;
  sumFlexEnd: number;
  paidOutFlex: number;
  pause1StartedAt: string;
  pause1StoppedAt: string;
  pause2StartedAt: string;
  pause2StoppedAt: string;
  pause10StartedAt: string;
  pause10StoppedAt: string;
  pause11StartedAt: string;
  pause11StoppedAt: string;
  pause12StartedAt: string;
  pause12StoppedAt: string;
  pause13StartedAt: string;
  pause13StoppedAt: string;
  pause14StartedAt: string;
  pause14StoppedAt: string;
  pause15StartedAt: string;
  pause15StoppedAt: string;
  pause16StartedAt: string;
  pause16StoppedAt: string;
  pause17StartedAt: string;
  pause17StoppedAt: string;
  pause18StartedAt: string;
  pause18StoppedAt: string;
  pause19StartedAt: string;
  pause19StoppedAt: string;
  pause100StartedAt: string;
  pause100StoppedAt: string;
  pause101StartedAt: string;
  pause101StoppedAt: string;
  pause102StartedAt: string;
  pause102StoppedAt: string;
  pause20StartedAt: string;
  pause20StoppedAt: string;
  pause21StartedAt: string;
  pause21StoppedAt: string;
  pause22StartedAt: string;
  pause22StoppedAt: string;
  pause23StartedAt: string;
  pause23StoppedAt: string;
  pause24StartedAt: string;
  pause24StoppedAt: string;
  pause25StartedAt: string;
  pause25StoppedAt: string;
  pause26StartedAt: string;
  pause26StoppedAt: string;
  pause27StartedAt: string;
  pause27StoppedAt: string;
  pause28StartedAt: string;
  pause28StoppedAt: string;
  pause29StartedAt: string;
  pause29StoppedAt: string;
  pause200StartedAt: string;
  pause200StoppedAt: string;
  pause201StartedAt: string;
  pause201StoppedAt: string;
  pause202StartedAt: string;
  pause202StoppedAt: string;
  pause3StartedAt: string;
  pause3StoppedAt: string;
  pause4StartedAt: string;
  pause4StoppedAt: string;
  pause5StartedAt: string;
  pause5StoppedAt: string;
  start1Id: number;
  stop1Id: number;
  pause1Id: number;
  start2Id: number;
  stop2Id: number;
  pause2Id: number;
  start3Id: number;
  stop3Id: number;
  pause3Id: number;
  start4Id: number;
  stop4Id: number;
  pause4Id: number;
  start5Id: number;
  stop5Id: number;
  pause5Id: number;
  // Request-only: exact-minute pause durations sent under UseOneMinuteIntervals=true.
  // Backend translates these into Pause*StartedAt/Pause*StoppedAt timestamp pairs.
  pause1ExactMinutes?: number;
  pause2ExactMinutes?: number;
  pause3ExactMinutes?: number;
  pause4ExactMinutes?: number;
  pause5ExactMinutes?: number;
  start1ExactMinutes?: number | null;
  start2ExactMinutes?: number | null;
  start3ExactMinutes?: number | null;
  start4ExactMinutes?: number | null;
  start5ExactMinutes?: number | null;
  stop1ExactMinutes?: number | null;
  stop2ExactMinutes?: number | null;
  stop3ExactMinutes?: number | null;
  stop4ExactMinutes?: number | null;
  stop5ExactMinutes?: number | null;
  nettoHoursOverride: number;
  nettoHoursOverrideActive: boolean;
  // Admin/manual pause override (Approach C). camelCase names match the C# DTO
  // (Pause{N}OverrideMinutes / Pause{N}OverrideMinutesSpecified / ClearPauseOverrides)
  // so JSON binds on the PUT body. null = compute pause from recorded slots;
  // non-null = authoritative total pause MINUTES for that shift. The companion
  // *Specified booleans distinguish "explicitly set/clear this shift" from
  // "not sent" (int? cannot tell null from omitted on the wire). clearPauseOverrides
  // reverts ALL five shifts to compute-from-slots in one shot. The worker's
  // recorded Pause*StartedAt/StoppedAt are never destroyed by these.
  pause1OverrideMinutes?: number | null;
  pause2OverrideMinutes?: number | null;
  pause3OverrideMinutes?: number | null;
  pause4OverrideMinutes?: number | null;
  pause5OverrideMinutes?: number | null;
  pause1OverrideMinutesSpecified?: boolean;
  pause2OverrideMinutesSpecified?: boolean;
  pause3OverrideMinutesSpecified?: boolean;
  pause4OverrideMinutesSpecified?: boolean;
  pause5OverrideMinutesSpecified?: boolean;
  clearPauseOverrides?: boolean;
}
