import { HelpEntry } from './help.model';

export const PLANNING_HELP_ENTRIES: HelpEntry[] = [
  // ---- tasks (no anchor, no tour) ----
  { id: 'task.registerVacation', kind: 'task', section: 'task',
    related: ['dayCell.flags', 'dayCell.nettoOverride', 'dayCell.save'] },
  { id: 'task.registerSickness', kind: 'task', section: 'task',
    related: ['dayCell.flags', 'dayCell.save'] },
  { id: 'task.registerDayOff', kind: 'task', section: 'task',
    related: ['dayCell.flags', 'dayCell.nettoOverride'] },
  { id: 'task.correctRegisteredTime', kind: 'task', section: 'task',
    related: ['dayCell.actualTimes', 'dayCell.resetField', 'dayCell.save'] },
  { id: 'task.addMissingRegistration', kind: 'task', section: 'task',
    related: ['grid.openDay', 'dayCell.actualTimes', 'dayCell.save'] },
  { id: 'task.addExtraShift', kind: 'task', section: 'task',
    related: ['dayCell.shiftCount', 'grid.settingsStrip'] },
  { id: 'task.changePlannedHours', kind: 'task', section: 'task',
    related: ['dayCell.plannedTimes', 'dayCell.planHours', 'dayCell.planHoursLimit'] },
  { id: 'task.payOutFlex', kind: 'task', section: 'task',
    related: ['dayCell.paidOutFlex', 'flex.sumFlex'] },
  { id: 'task.exportForPayroll', kind: 'task', section: 'task',
    related: ['toolbar.downloadExcel', 'toolbar.payrollExport'] },
  { id: 'task.whoChangedThis', kind: 'task', section: 'task',
    related: ['dayCell.versionHistory'] },
  { id: 'task.whereWasThisRegistered', kind: 'task', section: 'task',
    related: ['dayCell.gps', 'dayCell.snapshot'] },
  { id: 'task.filterToOneTeam', kind: 'task', section: 'task',
    related: ['toolbar.tagFilter', 'grid.tagChips'] },

  // ---- toolbar ----
  { id: 'toolbar.showResigned', kind: 'control', section: 'toolbar', anchor: 'toolbar.showResigned' },
  { id: 'toolbar.navBackward', kind: 'control', section: 'toolbar', anchor: 'toolbar.navBackward' },
  { id: 'toolbar.navForward', kind: 'control', section: 'toolbar', anchor: 'toolbar.navForward',
    tour: 'page', tourStep: 2 },
  { id: 'toolbar.workerFilter', kind: 'control', section: 'toolbar', anchor: 'toolbar.workerFilter',
    tour: 'page', tourStep: 3 },
  { id: 'toolbar.tagFilter', kind: 'control', section: 'toolbar', anchor: 'toolbar.tagFilter' },
  { id: 'toolbar.dateRange', kind: 'control', section: 'toolbar', anchor: 'toolbar.dateRange',
    tour: 'page', tourStep: 1 },
  { id: 'toolbar.downloadExcel', kind: 'control', section: 'toolbar', anchor: 'toolbar.downloadExcel',
    tour: 'page', tourStep: 6 },
  { id: 'toolbar.payrollExport', kind: 'control', section: 'toolbar', anchor: 'toolbar.payrollExport',
    tour: 'page', tourStep: 7, adminOnly: true },
  { id: 'toolbar.reload', kind: 'control', section: 'toolbar', anchor: 'toolbar.reload' },

  // ---- grid ----
  { id: 'grid.nameColumn', kind: 'control', section: 'grid', anchor: 'grid.nameColumn',
    tour: 'page', tourStep: 4 },
  { id: 'grid.tagChips', kind: 'control', section: 'grid', anchor: 'grid.tagChips' },
  { id: 'grid.settingsStrip', kind: 'control', section: 'grid', anchor: 'grid.settingsStrip' },
  { id: 'grid.dayCellAnatomy', kind: 'control', section: 'grid', anchor: 'grid.dayCellAnatomy',
    tour: 'page', tourStep: 5 },
  { id: 'grid.weeklyPlannedHours', kind: 'control', section: 'grid', anchor: 'grid.weeklyPlannedHours' },
  { id: 'grid.messageIcons', kind: 'control', section: 'grid', anchor: 'grid.messageIcons' },
  { id: 'grid.sortName', kind: 'control', section: 'grid', anchor: 'grid.sortName' },
  { id: 'grid.openDay', kind: 'control', section: 'grid', anchor: 'grid.openDay',
    tour: 'page', tourStep: 8 },
  { id: 'grid.noWorkers', kind: 'control', section: 'grid', anchor: 'grid.noWorkers' },

  // ---- day-cell dialog ----
  { id: 'dayCell.versionHistory', kind: 'control', section: 'dayCell', anchor: 'dayCell.versionHistory' },
  { id: 'dayCell.plannedTimes', kind: 'control', section: 'dayCell', anchor: 'dayCell.plannedTimes',
    tour: 'dialog', tourStep: 1 },
  { id: 'dayCell.actualTimes', kind: 'control', section: 'dayCell', anchor: 'dayCell.actualTimes',
    tour: 'dialog', tourStep: 2 },
  { id: 'dayCell.shiftCount', kind: 'control', section: 'dayCell', anchor: 'dayCell.shiftCount' },
  { id: 'dayCell.resetField', kind: 'control', section: 'dayCell', anchor: 'dayCell.resetField' },
  { id: 'dayCell.resetPauseToRecorded', kind: 'control', section: 'dayCell', anchor: 'dayCell.resetPauseToRecorded' },
  { id: 'dayCell.gps', kind: 'control', section: 'dayCell', anchor: 'dayCell.gps' },
  { id: 'dayCell.snapshot', kind: 'control', section: 'dayCell', anchor: 'dayCell.snapshot' },
  { id: 'dayCell.futureDisabled', kind: 'control', section: 'dayCell', anchor: 'dayCell.futureDisabled' },
  { id: 'dayCell.planHours', kind: 'control', section: 'dayCell', anchor: 'dayCell.planHours',
    tour: 'dialog', tourStep: 3 },
  { id: 'dayCell.nettoOverride', kind: 'control', section: 'dayCell', anchor: 'dayCell.nettoOverride',
    tour: 'dialog', tourStep: 5 },
  { id: 'dayCell.paidOutFlex', kind: 'control', section: 'dayCell', anchor: 'dayCell.paidOutFlex' },
  { id: 'dayCell.flags', kind: 'control', section: 'dayCell', anchor: 'dayCell.flags',
    tour: 'dialog', tourStep: 4 },
  { id: 'dayCell.commentOffice', kind: 'control', section: 'dayCell', anchor: 'dayCell.commentOffice' },
  { id: 'dayCell.save', kind: 'control', section: 'dayCell', anchor: 'dayCell.save',
    tour: 'dialog', tourStep: 6 },
  { id: 'dayCell.oneMinuteIntervals', kind: 'control', section: 'dayCell', anchor: 'dayCell.oneMinuteIntervals' },
  { id: 'dayCell.planHoursLimit', kind: 'control', section: 'dayCell', anchor: 'dayCell.planHoursLimit' },

  // ---- flex ----
  { id: 'flex.whatIsFlex', kind: 'control', section: 'flex', anchor: 'flex.whatIsFlex' },
  { id: 'flex.sumFlex', kind: 'control', section: 'flex', anchor: 'flex.sumFlex' },
  { id: 'flex.paidOutFlexRelation', kind: 'control', section: 'flex', anchor: 'flex.paidOutFlexRelation' },
];
