using System;

namespace TimePlanning.Pn.Infrastructure.Models.WorkingHours.UpdateCreate;

public class TimePlanningWorkingHoursUpdateModel
{
    public DateTime Date { get; set; }
    public int? Shift1Start { get; set; }
    public int? Shift1Pause { get; set; }
    public int? Shift1Stop { get; set; }
    public int? Shift2Start { get; set; }
    public int? Shift2Pause { get; set; }
    public int? Shift2Stop { get; set; }
    public int? Shift3Start { get; set; }
    public int? Shift3Pause { get; set; }
    public int? Shift3Stop { get; set; }
    public int? Shift4Start { get; set; }
    public int? Shift4Pause { get; set; }
    public int? Shift4Stop { get; set; }
    public int? Shift5Start { get; set; }
    public int? Shift5Pause { get; set; }
    public int? Shift5Stop { get; set; }
    public string CommentWorker { get; set; }
    public string Start1StartedAt { get; set; }
    public string Stop1StoppedAt { get; set; }
    public string Pause1StartedAt { get; set; }
    public string Pause1StoppedAt { get; set; }
    public string Start2StartedAt { get; set; }
    public string Stop2StoppedAt { get; set; }
    public string Start3StartedAt { get; set; }
    public string Stop3StoppedAt { get; set; }
    public string Start4StartedAt { get; set; }
    public string Stop4StoppedAt { get; set; }
    public string Start5StartedAt { get; set; }
    public string Stop5StoppedAt { get; set; }
    public string Pause2StartedAt { get; set; }
    public string Pause2StoppedAt { get; set; }
    public string Pause10StartedAt { get; set; }
    public string Pause10StoppedAt { get; set; }
    public string Pause11StartedAt { get; set; }
    public string Pause11StoppedAt { get; set; }
    public string Pause12StartedAt { get; set; }
    public string Pause12StoppedAt { get; set; }
    public string Pause13StartedAt { get; set; }
    public string Pause13StoppedAt { get; set; }
    public string Pause14StartedAt { get; set; }
    public string Pause14StoppedAt { get; set; }
    public string Pause15StartedAt { get; set; }
    public string Pause15StoppedAt { get; set; }
    public string Pause16StartedAt { get; set; }
    public string Pause16StoppedAt { get; set; }
    public string Pause17StartedAt { get; set; }
    public string Pause17StoppedAt { get; set; }
    public string Pause18StartedAt { get; set; }
    public string Pause18StoppedAt { get; set; }
    public string Pause19StartedAt { get; set; }
    public string Pause19StoppedAt { get; set; }
    public string Pause100StartedAt { get; set; }
    public string Pause100StoppedAt { get; set; }
    public string Pause101StartedAt { get; set; }
    public string Pause101StoppedAt { get; set; }
    public string Pause102StartedAt { get; set; }
    public string Pause102StoppedAt { get; set; }
    public string Pause20StartedAt { get; set; }
    public string Pause20StoppedAt { get; set; }
    public string Pause21StartedAt { get; set; }
    public string Pause21StoppedAt { get; set; }
    public string Pause22StartedAt { get; set; }
    public string Pause22StoppedAt { get; set; }
    public string Pause23StartedAt { get; set; }
    public string Pause23StoppedAt { get; set; }
    public string Pause24StartedAt { get; set; }
    public string Pause24StoppedAt { get; set; }
    public string Pause25StartedAt { get; set; }
    public string Pause25StoppedAt { get; set; }
    public string Pause26StartedAt { get; set; }
    public string Pause26StoppedAt { get; set; }
    public string Pause27StartedAt { get; set; }
    public string Pause27StoppedAt { get; set; }
    public string Pause28StartedAt { get; set; }
    public string Pause28StoppedAt { get; set; }
    public string Pause29StartedAt { get; set; }
    public string Pause29StoppedAt { get; set; }
    public string Pause200StartedAt { get; set; }
    public string Pause200StoppedAt { get; set; }
    public string Pause201StartedAt { get; set; }
    public string Pause201StoppedAt { get; set; }
    public string Pause202StartedAt { get; set; }
    public string Pause202StoppedAt { get; set; }
    public string Pause3StartedAt { get; set; }
    public string Pause3StoppedAt { get; set; }
    public string Pause4StartedAt { get; set; }
    public string Pause4StoppedAt { get; set; }
    public string Pause5StartedAt { get; set; }
    public string Pause5StoppedAt { get; set; }
    public int Shift1PauseNumber { get; set; }
    public int Shift2PauseNumber { get; set; }
    public string SoftwareVersion { get; set; }
    public string Model { get; set; }
    public string Manufacturer { get; set; }
    public string OsVersion { get; set; }
}