//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimePlanning.Pn.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations_hr_HR {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_hr_HR() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TimePlanning.Pn.Resources.Translations.hr-HR", typeof(Translations_hr_HR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Shift_1__start {
            get {
                return ResourceManager.GetString("Shift 1: start", resourceCulture);
            }
        }
        
        internal static string PlanText {
            get {
                return ResourceManager.GetString("PlanText", resourceCulture);
            }
        }
        
        internal static string PlanHours {
            get {
                return ResourceManager.GetString("PlanHours", resourceCulture);
            }
        }
        
        internal static string Shift_1__pause {
            get {
                return ResourceManager.GetString("Shift 1: pause", resourceCulture);
            }
        }
        
        internal static string Shift_1__end {
            get {
                return ResourceManager.GetString("Shift 1: end", resourceCulture);
            }
        }
        
        internal static string Shift_2__start {
            get {
                return ResourceManager.GetString("Shift 2: start", resourceCulture);
            }
        }
        
        internal static string Shift_2__pause {
            get {
                return ResourceManager.GetString("Shift 2: pause", resourceCulture);
            }
        }
        
        internal static string Shift_2__end {
            get {
                return ResourceManager.GetString("Shift 2: end", resourceCulture);
            }
        }
        
        internal static string NettoHours {
            get {
                return ResourceManager.GetString("NettoHours", resourceCulture);
            }
        }
        
        internal static string Flex {
            get {
                return ResourceManager.GetString("Flex", resourceCulture);
            }
        }
        
        internal static string SumFlexStart {
            get {
                return ResourceManager.GetString("SumFlexStart", resourceCulture);
            }
        }
        
        internal static string SumFlexEnd {
            get {
                return ResourceManager.GetString("SumFlexEnd", resourceCulture);
            }
        }
        
        internal static string PaidOutFlex {
            get {
                return ResourceManager.GetString("PaidOutFlex", resourceCulture);
            }
        }
        
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        internal static string Comment_office {
            get {
                return ResourceManager.GetString("Comment office", resourceCulture);
            }
        }
        
        internal static string Comment_office_all {
            get {
                return ResourceManager.GetString("Comment office all", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
        
        internal static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        internal static string Employee_no {
            get {
                return ResourceManager.GetString("Employee no", resourceCulture);
            }
        }
        
        internal static string PlanRegistrationFound {
            get {
                return ResourceManager.GetString("PlanRegistrationFound", resourceCulture);
            }
        }
        
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        internal static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        internal static string Shift_3__start {
            get {
                return ResourceManager.GetString("Shift 3: start", resourceCulture);
            }
        }
        
        internal static string Shift_3__end {
            get {
                return ResourceManager.GetString("Shift 3: end", resourceCulture);
            }
        }
        
        internal static string Shift_3__pause {
            get {
                return ResourceManager.GetString("Shift 3: pause", resourceCulture);
            }
        }
        
        internal static string Shift_4__start {
            get {
                return ResourceManager.GetString("Shift 4: start", resourceCulture);
            }
        }
        
        internal static string Shift_4__end {
            get {
                return ResourceManager.GetString("Shift 4: end", resourceCulture);
            }
        }
        
        internal static string Shift_4__pause {
            get {
                return ResourceManager.GetString("Shift 4: pause", resourceCulture);
            }
        }
        
        internal static string Shift_5__start {
            get {
                return ResourceManager.GetString("Shift 5: start", resourceCulture);
            }
        }
        
        internal static string Shift_5__end {
            get {
                return ResourceManager.GetString("Shift 5: end", resourceCulture);
            }
        }
        
        internal static string Shift_5__pause {
            get {
                return ResourceManager.GetString("Shift 5: pause", resourceCulture);
            }
        }
        
        internal static string Week_number {
            get {
                return ResourceManager.GetString("Week number", resourceCulture);
            }
        }
        
        internal static string Hours_Saturday {
            get {
                return ResourceManager.GetString("Hours Saturday", resourceCulture);
            }
        }
        
        internal static string Hours_Sunday {
            get {
                return ResourceManager.GetString("Hours Sunday", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string Total_Hours {
            get {
                return ResourceManager.GetString("Total Hours", resourceCulture);
            }
        }
    }
}
